permalink:              pretty
relative_permalinks:    true

title:                  argp
tagline:
# tagline:              The third argument to ioctl() is traditionally named char *argp.
url:                    https://argp.github.io
baseurl:                "https://argp.github.io"
# baseurl:

sass:
    sass_dir:           _sass
    style:              :compressed

author:
    name:               argp
    url:
    email:              argp@census-labs.com

version:                6.66
github:
repo:                   https://github.com/argp/argp.github.io

pages_list:
    posts:              '/posts'
    research:           '/research'
    advisories:         '/advisories'

# EOF
