permalink:              pretty
relative_permalinks:    true

title:                  argp
tagline:
url:                    http://argp.github.io
baseurl:                "http://argp.github.io"
# baseurl:

sass:
    sass_dir:           _sass
    style:              :compressed

author:
    name:               argp
    url:
    email:              argp@census-labs.com

version:                6.66
github:
repo:                   https://github.com/argp/argp.github.io

pages_list:
    posts:              '/posts'
    research:           '/research'
    bugs:               '/bugs'

# EOF
