# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               argp
tagline:
url:                 http://argp.github.io
paginate:            1
baseurl:             "http://argp.github.io/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              argp
  url:
  email:             argp@census-labs.com

# Custom vars
version:             2.0.0
github:
repo:                https://github.com/argp/argp.github.io

# EOF
